development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a80be46bf497834b47b7c27bd4ad13b0@scat.redistogo.com:11992/
  # channel_prefix: Chat_Point_production
